import pytest

from pybotters_wrapper.bitbank.price_size_precision_fetcher import (
    bitbankPriceSizePrecisionFetcher,
)


@pytest.mark.skip(reason="Calls real API")
def test_price_size_precision_fetcher():
    expected = {
        "price": {
            "btc_jpy": 0,
            "xrp_jpy": 3,
            "eth_jpy": 0,
            "matic_jpy": 3,
            "dot_jpy": 3,
            "doge_jpy": 3,
            "ltc_jpy": 1,
            "bcc_jpy": 0,
            "mona_jpy": 3,
            "xlm_jpy": 3,
            "qtum_jpy": 3,
            "bat_jpy": 3,
            "omg_jpy": 3,
            "xym_jpy": 3,
            "link_jpy": 3,
            "mkr_jpy": 0,
            "boba_jpy": 3,
            "enj_jpy": 3,
            "astr_jpy": 3,
            "ada_jpy": 3,
            "avax_jpy": 3,
            "axs_jpy": 3,
            "flr_jpy": 3,
            "sand_jpy": 3,
            "gala_jpy": 3,
            "chz_jpy": 3,
            "ape_jpy": 3,
            "oas_jpy": 3,
            "mana_jpy": 3,
            "grt_jpy": 3,
            "xrp_btc": 8,
            "eth_btc": 8,
            "ltc_btc": 8,
            "bcc_btc": 8,
            "mona_btc": 8,
            "xlm_btc": 8,
            "qtum_btc": 8,
            "bat_btc": 8,
            "omg_btc": 8,
            "xym_btc": 8,
            "link_btc": 8,
            "mkr_btc": 8,
            "boba_btc": 8,
            "enj_btc": 8,
            "matic_btc": 8,
        },
        "size": {
            "btc_jpy": 4,
            "xrp_jpy": 4,
            "eth_jpy": 4,
            "matic_jpy": 4,
            "dot_jpy": 4,
            "doge_jpy": 4,
            "ltc_jpy": 4,
            "bcc_jpy": 4,
            "mona_jpy": 4,
            "xlm_jpy": 4,
            "qtum_jpy": 4,
            "bat_jpy": 4,
            "omg_jpy": 4,
            "xym_jpy": 4,
            "link_jpy": 4,
            "mkr_jpy": 4,
            "boba_jpy": 4,
            "enj_jpy": 4,
            "astr_jpy": 4,
            "ada_jpy": 4,
            "avax_jpy": 4,
            "axs_jpy": 4,
            "flr_jpy": 4,
            "sand_jpy": 4,
            "gala_jpy": 4,
            "chz_jpy": 4,
            "ape_jpy": 4,
            "oas_jpy": 4,
            "mana_jpy": 4,
            "grt_jpy": 4,
            "xrp_btc": 4,
            "eth_btc": 4,
            "ltc_btc": 4,
            "bcc_btc": 4,
            "mona_btc": 3,
            "xlm_btc": 4,
            "qtum_btc": 4,
            "bat_btc": 4,
            "omg_btc": 4,
            "xym_btc": 4,
            "link_btc": 4,
            "mkr_btc": 4,
            "boba_btc": 4,
            "enj_btc": 4,
            "matic_btc": 4,
        },
    }
    fetcher = bitbankPriceSizePrecisionFetcher()

    actual = fetcher.fetch_precisions()

    assert expected == actual
